require('dotenv').config()
const express = require('express')
const cors = require('cors')
const cookieParser = require('cookie-parser')
const path = require('path')
const ejs = require('ejs')
const router = require('./src/routes/router')
const app = express()
const admin = require('./src/routes/admin/admin-router')
const user = require('./src/routes/user/user-router')

app.use(cors())
app.use(cookieParser())
app.use(express.json())
app.use(express.urlencoded({ extended: true }))
app.use('/public', express.static(path.join(process.cwd(), 'public')))
app.set('view engine', 'ejs')
app.set('views', path.join(process.cwd(), 'src', 'views'))
app.use(router)
app.use(admin)
app.use(user)
    .listen(6060, console.log(6060))